### ISSUE TITLE
Additional documentation

### ISSUE THREAD

**Issue by hasii2011** [rawfh/orthogonal-drawing-algorithm#1]
Do you have any additional documentation on this repository?  I would like to use the layout algorithm in my Python project

**Comment by hasii2011** [comment]
Hope you are Ok with my fork here:  https://github.com/hasii2011/OrthogonalDrawing

**Comment by hasii2011** [comment]
Still using it

**Comment by rawfh** [comment]
So sorry for getting back to you so late, I have added some content in README. If you need more information, I am willing to answer.

**Comment by hasii2011** [comment]
Thanks for the update especially the academic reference.  In order to understand and use the code I actually forked the project here. https://github.com/hasii2011/OrthogonalDrawing
